// lib/festivals.js — the month-wise festival guide (content compiled from the festival list the owner supplied, checked and
// completed). `k` points into FESTIVAL_DATES (lunisolar tithi festivals, exact tithi windows computed with Swiss Ephemeris);
// `sol` marks Sun-ingress festivals (Mesha = 0, Makara = 9); `info` has no computed date (regional / solar-Malayalam / folk).
export const MONTH_ORDER = ['chaitra','vaishakha','jyeshtha','ashadha','shravana','bhadrapada','ashvina','kartika','margashirsha','pausha','magha','phalguna'];
export const MONTH_NAMES = {
  chaitra: ['चैत्र', 'Chaitra'], vaishakha: ['वैशाख', 'Vaishakha'], jyeshtha: ['ज्येष्ठ', 'Jyeshtha'], ashadha: ['आषाढ़', 'Ashadha'], shravana: ['श्रावण (सावन)', 'Shravana (Sawan)'],
  bhadrapada: ['भाद्रपद (भादो)', 'Bhadrapada (Bhado)'], ashvina: ['आश्विन (क्वार)', 'Ashvina (Kwar)'], kartika: ['कार्तिक', 'Kartika'], margashirsha: ['मार्गशीर्ष', 'Margashirsha'],
  pausha: ['पौष', 'Pausha'], magha: ['माघ', 'Magha'], phalguna: ['फाल्गुन', 'Phalguna'],
};
const T = (m, hi, en, dh, de, extra = {}) => ({ m, hi, en, dh, de, ...extra });

export const FESTIVALS = [
  // ── Chaitra ──
  T('chaitra', 'चैत्र नवरात्रि', 'Chaitra Navratri', 'शुक्ल प्रतिपदा से नवमी — घटस्थापना, देवी के 9 रूपों की पूजा, कन्या पूजन।', 'Shukla Pratipada to Navami — ghatasthapana, worship of the nine forms of the Goddess, kanya pujan.', { k: 'chaitra_navratri', end: 'chaitra_navami', rule: ['चैत्र शुक्ल प्रतिपदा', 'Chaitra Shukla Pratipada'], r: 'all' }),
  T('chaitra', 'गुड़ी पड़वा / उगादि', 'Gudi Padwa / Ugadi', 'महाराष्ट्र व दक्षिण भारत (कर्नाटक, आंध्र, तेलंगाना) में नववर्ष।', 'New Year in Maharashtra and South India (Karnataka, Andhra, Telangana).', { k: 'chaitra_navratri', rule: ['चैत्र शुक्ल प्रतिपदा', 'Chaitra Shukla Pratipada'], r: 'west-south' }),
  T('chaitra', 'विशु (केरल नववर्ष)', 'Vishu (Kerala New Year)', 'केरल में ‘विशुक्कणी’ दर्शन और बड़ों द्वारा ‘विशुक्कैनीटम’ (उपहार) देना। मेष संक्रांति के दिन।', 'In Kerala, the first sight of the ‘Vishukkani’ and elders giving ‘Vishukkaineettam’ gifts. Falls at Mesha Sankranti.', { sol: 0, r: 'south' }),
  T('chaitra', 'बोहाग बिहू / रोंगाली बिहू (असम)', 'Bohag / Rongali Bihu (Assam)', 'असमिया नववर्ष, पारंपरिक नृत्य और फसल उत्सव। मेष संक्रांति के आसपास।', 'Assamese New Year, traditional dance and a harvest festival. Around Mesha Sankranti.', { sol: 0, r: 'east' }),
  T('chaitra', 'पोहिला बोइशाख (बंगाल)', 'Pohela Boishakh (Bengal)', 'बंगाली नववर्ष, नए बही-खातों (हाल खाता) की शुरुआत। मेष संक्रांति के आसपास।', 'Bengali New Year, the start of new account books (Haal Khata). Around Mesha Sankranti.', { sol: 0, r: 'east' }),
  T('chaitra', 'शीतला अष्टमी / बसौड़ा', 'Sheetala Ashtami / Basoda', 'कृष्ण अष्टमी — बासी भोजन (हलवा-पूरी) का भोग व पूजन।', 'Krishna Ashtami — worship with the previous day’s cooked food (halwa-puri) as offering.', { k: 'sheetala_ashtami', rule: ['चैत्र कृष्ण अष्टमी', 'Chaitra Krishna Ashtami'], r: 'north' }),
  T('chaitra', 'गणगौर', 'Gangaur', 'शुक्ल तृतीया — राजस्थान व मध्य प्रदेश में ईसर-गौरा पूजन (16 दिन) और विसर्जन।', 'Shukla Tritiya — Isar-Gaura worship (16 days) and immersion in Rajasthan and Madhya Pradesh.', { k: 'gangaur', rule: ['चैत्र शुक्ल तृतीया', 'Chaitra Shukla Tritiya'], r: 'north-west' }),
  T('chaitra', 'रामनवमी', 'Ram Navami', 'शुक्ल नवमी — भगवान श्री राम का जन्मोत्सव, रामचरितमानस पाठ।', 'Shukla Navami — birth anniversary of Lord Ram, Ramcharitmanas recitation.', { k: 'chaitra_navami', rule: ['चैत्र शुक्ल नवमी', 'Chaitra Shukla Navami'], r: 'all', guide: 'aarti/hanuman-chalisa' }),
  T('chaitra', 'हनुमान जयंती', 'Hanuman Jayanti', 'पूर्णिमा — सिन्दूर चोला अर्पण, सुंदरकांड व हनुमान चालीसा पाठ।', 'Purnima — offering sindoor, Sundarkand and Hanuman Chalisa recitation.', { k: 'hanuman_jayanti', rule: ['चैत्र पूर्णिमा', 'Chaitra Purnima'], r: 'north', guide: 'aarti/hanuman-chalisa' }),
  // ── Vaishakha ──
  T('vaishakha', 'वैशाखी', 'Vaisakhi', 'पंजाब व हरियाणा में फसल कटाई का उत्सव और खालसा पंथ की स्थापना। मेष संक्रांति के आसपास।', 'Harvest festival in Punjab and Haryana and the founding of the Khalsa. Around Mesha Sankranti.', { sol: 0, r: 'north' }),
  T('vaishakha', 'सीता नवमी / जानकी जयंती', 'Sita Navami / Janaki Jayanti', 'शुक्ल नवमी — राजा जनक को भूमि से सीता जी की प्राप्ति।', 'Shukla Navami — King Janaka’s finding of Sita in the earth.', { k: 'sita_navami', rule: ['वैशाख शुक्ल नवमी', 'Vaishakha Shukla Navami'], r: 'all' }),
  T('vaishakha', 'अक्षय तृतीया', 'Akshaya Tritiya', 'शुक्ल तृतीया — दान-पुण्य, सोना/बर्तन की ख़रीद, अबूझ मुहूर्त।', 'Shukla Tritiya — charity, buying gold or utensils, an all-day auspicious time.', { k: 'akshaya_tritiya', rule: ['वैशाख शुक्ल तृतीया', 'Vaishakha Shukla Tritiya'], r: 'all' }),
  T('vaishakha', 'नरसिंह जयंती', 'Narasimha Jayanti', 'शुक्ल चतुर्दशी — भगवान विष्णु के नरसिंह अवतार का पूजन व व्रत।', 'Shukla Chaturdashi — worship and fast for Vishnu’s Narasimha avatar.', { k: 'narasimha_jayanti', rule: ['वैशाख शुक्ल चतुर्दशी', 'Vaishakha Shukla Chaturdashi'], r: 'all' }),
  // ── Jyeshtha ──
  T('jyeshtha', 'वट सावित्री व्रत', 'Vat Savitri Vrat', 'अमावस्या — सावित्री-सत्यवान कथा, वट वृक्ष की परिक्रमा।', 'Amavasya — the Savitri–Satyavan katha and circumambulation of the banyan tree.', { k: 'vat_savitri', rule: ['ज्येष्ठ अमावस्या', 'Jyeshtha Amavasya'], r: 'north' }),
  T('jyeshtha', 'गंगा दशहरा', 'Ganga Dussehra', 'शुक्ल दशमी — माँ गंगा का धरती पर अवतरण; दस प्रकार की वस्तुओं का दान।', 'Shukla Dashami — the descent of Ganga to earth; donating ten kinds of items.', { k: 'ganga_dussehra', rule: ['ज्येष्ठ शुक्ल दशमी', 'Jyeshtha Shukla Dashami'], r: 'north' }),
  T('jyeshtha', 'निर्जला एकादशी', 'Nirjala Ekadashi', 'शुक्ल एकादशी — बिना जल का कठिन उपवास; जलपात्र व फल का दान।', 'Shukla Ekadashi — the strictest fast, without water; donating water pots and fruit.', { k: 'nirjala_ekadashi', rule: ['ज्येष्ठ शुक्ल एकादशी', 'Jyeshtha Shukla Ekadashi'], r: 'all', guide: 'vrat/ekadashi' }),
  // ── Ashadha ──
  T('ashadha', 'जगन्नाथ रथ यात्रा', 'Jagannath Rath Yatra', 'शुक्ल द्वितीया — पुरी (ओडिशा) में भगवान जगन्नाथ, बलभद्र व सुभद्रा की भव्य रथयात्रा।', 'Shukla Dwitiya — the grand chariot festival of Jagannath, Balabhadra and Subhadra at Puri, Odisha.', { k: 'rath_yatra', rule: ['आषाढ़ शुक्ल द्वितीया', 'Ashadha Shukla Dwitiya'], r: 'east' }),
  T('ashadha', 'देवशयनी एकादशी', 'Devshayani Ekadashi', 'शुक्ल एकादशी — भगवान विष्णु का चार माह का शयन; चातुर्मास का आरंभ।', 'Shukla Ekadashi — Vishnu’s four-month rest; the start of Chaturmas.', { k: 'devshayani', rule: ['आषाढ़ शुक्ल एकादशी', 'Ashadha Shukla Ekadashi'], r: 'all', guide: 'vrat/ekadashi' }),
  T('ashadha', 'गुरु पूर्णिमा', 'Guru Purnima', 'पूर्णिमा — महर्षि वेदव्यास का जन्मोत्सव, गुरु पूजन।', 'Purnima — the birth anniversary of Maharshi Vyasa; worship of the guru.', { k: 'guru_purnima', rule: ['आषाढ़ पूर्णिमा', 'Ashadha Purnima'], r: 'all', guide: 'vrat/purnima' }),
  // ── Shravana ──
  T('shravana', 'सावन सोमवार', 'Sawan Somvar', 'श्रावण के सोमवार — भगवान शिव का जलाभिषेक, दूध और बेलपत्र अर्पण।', 'Mondays of Shravana — abhishek of Lord Shiva with water, milk and bel leaves.', { info: true, r: 'all', guide: 'aarti/shiv-aarti' }),
  T('shravana', 'नागपंचमी', 'Nag Panchami', 'शुक्ल पंचमी — नाग देव का पूजन; दूध व लावा अर्पण।', 'Shukla Panchami — worship of the Nag deities with milk and puffed rice.', { k: 'nag_panchami', rule: ['श्रावण शुक्ल पंचमी', 'Shravana Shukla Panchami'], r: 'all' }),
  T('shravana', 'हरियाली तीज', 'Hariyali Teej', 'शुक्ल तृतीया — उत्तर भारत में शिव-पार्वती पुनर्मिलन; सुहाग सामग्री अर्पण।', 'Shukla Tritiya — the reunion of Shiva and Parvati celebrated in North India; offering of suhag items.', { k: 'hariyali_teej', rule: ['श्रावण शुक्ल तृतीया', 'Shravana Shukla Tritiya'], r: 'north' }),
  T('shravana', 'रक्षाबंधन / कजरिया', 'Raksha Bandhan / Kajaria', 'पूर्णिमा — रक्षासूत्र बाँधना; जौ की कजरियों का विसर्जन।', 'Purnima — tying the rakhi; immersion of barley shoots (kajariya).', { k: 'raksha_bandhan', rule: ['श्रावण पूर्णिमा', 'Shravana Purnima'], r: 'all', note: ['भद्रा काल में राखी नहीं बाँधी जाती — शुभ समय के लिए स्थानीय पंचांग देखें।', 'Rakhi is not tied during Bhadra — check a local almanac for the exact muhurat.'] }),
  // ── Bhadrapada ──
  T('bhadrapada', 'ओणम (केरल)', 'Onam (Kerala)', 'राजा बलि के स्वागत में पूक्कलम (फूलों की रंगोली) और सद्या (भोज)। मलयालम चिंगम मास का तिरुवोणम दिन।', 'Pookalam (flower rangoli) and the sadya feast welcoming King Mahabali. The Thiruvonam day of the Malayalam month Chingam.', { info: true, r: 'south' }),
  T('bhadrapada', 'कजरी तीज', 'Kajari Teej', 'कृष्ण तृतीया — सत्तू का भोग, नीमड़ी माता पूजन।', 'Krishna Tritiya — sattu offering and worship of Nimadi Mata.', { k: 'kajari_teej', rule: ['भाद्रपद कृष्ण तृतीया', 'Bhadrapada Krishna Tritiya'], r: 'north' }),
  T('bhadrapada', 'हलषष्ठी / ललही छठ', 'Halashashthi / Lalhi Chhath', 'कृष्ण षष्ठी — बलराम जन्मोत्सव; पसई चावल और भैंस के दूध का प्रयोग।', 'Krishna Shashthi — Balarama’s birth anniversary; use of pasai rice and buffalo milk.', { k: 'halashashthi', rule: ['भाद्रपद कृष्ण षष्ठी', 'Bhadrapada Krishna Shashthi'], r: 'north' }),
  T('bhadrapada', 'कृष्ण जन्माष्टमी', 'Krishna Janmashtami', 'कृष्ण अष्टमी — कान्हा का जन्मोत्सव, मटकी फोड़ (दही हांडी)।', 'Krishna Ashtami — Kanha’s birth anniversary, the dahi-handi pot-breaking.', { k: 'janmashtami', rule: ['भाद्रपद कृष्ण अष्टमी', 'Bhadrapada Krishna Ashtami'], r: 'all' }),
  T('bhadrapada', 'हरतालिका तीज', 'Hartalika Teej', 'शुक्ल तृतीया — बालू के शिव-पार्वती का पूजन; कठिन निर्जला व्रत।', 'Shukla Tritiya — worship of sand idols of Shiva-Parvati; a strict waterless fast.', { k: 'hartalika_teej', rule: ['भाद्रपद शुक्ल तृतीया', 'Bhadrapada Shukla Tritiya'], r: 'north' }),
  T('bhadrapada', 'गणेश चतुर्थी और गणपति विसर्जन', 'Ganesh Chaturthi & Visarjan', 'शुक्ल चतुर्थी से अनंत चतुर्दशी — महाराष्ट्र व पूरे भारत में 10 दिन गणेश पूजा।', 'Shukla Chaturthi to Anant Chaturdashi — ten days of Ganesh worship in Maharashtra and across India.', { k: 'ganesh_chaturthi', end: 'anant_chaturdashi', rule: ['भाद्रपद शुक्ल चतुर्थी', 'Bhadrapada Shukla Chaturthi'], r: 'all', guide: 'aarti/ganesh-aarti' }),
  T('bhadrapada', 'ऋषि पंचमी', 'Rishi Panchami', 'शुक्ल पंचमी — अपामार्ग स्नान; सप्तर्षि व अरुंधति का पूजन।', 'Shukla Panchami — a bath with apamarga; worship of the Saptarshis and Arundhati.', { k: 'rishi_panchami', rule: ['भाद्रपद शुक्ल पंचमी', 'Bhadrapada Shukla Panchami'], r: 'north' }),
  T('bhadrapada', 'संतान सप्तमी', 'Santan Saptami', 'शुक्ल सप्तमी — संतान की रक्षा हेतु डोरा धारण करना।', 'Shukla Saptami — wearing a protective thread for the well-being of children.', { k: 'santan_saptami', rule: ['भाद्रपद शुक्ल सप्तमी', 'Bhadrapada Shukla Saptami'], r: 'north' }),
  T('bhadrapada', 'राधाष्टमी', 'Radhashtami', 'शुक्ल अष्टमी — श्री राधा रानी के प्राकट्य दिवस का पूजन।', 'Shukla Ashtami — worship on the appearance day of Shri Radha.', { k: 'radhashtami', rule: ['भाद्रपद शुक्ल अष्टमी', 'Bhadrapada Shukla Ashtami'], r: 'north' }),
  T('bhadrapada', 'अनंत चतुर्दशी', 'Anant Chaturdashi', 'शुक्ल चतुर्दशी — 14 गाँठों वाला अनंत सूत्र धारण करना।', 'Shukla Chaturdashi — wearing the Anant thread with 14 knots.', { k: 'anant_chaturdashi', rule: ['भाद्रपद शुक्ल चतुर्दशी', 'Bhadrapada Shukla Chaturdashi'], r: 'all' }),
  // ── Ashvina ──
  T('ashvina', 'पितृपक्ष / श्राद्ध', 'Pitru Paksha / Shraddha', 'पूर्णिमा से अमावस्या तक 16 दिन — तर्पण, पिंडदान, पंचबली और ब्राह्मण भोजन।', 'Sixteen days from Purnima to Amavasya — tarpan, pind daan, panchabali and feeding Brahmins.', { k: 'pitru_start', end: 'pitru_end', rule: ['भाद्रपद पूर्णिमा से आश्विन अमावस्या', 'Bhadrapada Purnima to Ashvina Amavasya'], r: 'all', guide: 'vrat/shraddh' }),
  T('ashvina', 'जिउतिया / जीवितपुत्रिका', 'Jitiya / Jivitputrika', 'कृष्ण अष्टमी (बिहार/यूपी) — संतान की दीर्घायु के लिए 36 घंटे का निर्जला व्रत।', 'Krishna Ashtami (Bihar/UP) — a 36-hour waterless fast for the long life of children.', { k: 'jivitputrika', rule: ['आश्विन कृष्ण अष्टमी', 'Ashvina Krishna Ashtami'], r: 'east' }),
  T('ashvina', 'शारदीय नवरात्रि व दुर्गा पूजा', 'Sharad Navratri & Durga Puja', 'शुक्ल प्रतिपदा से नवमी — कलश स्थापना; बंगाल में भव्य दुर्गा पूजा पंडाल।', 'Shukla Pratipada to Navami — kalash sthapana; grand Durga Puja pandals in Bengal.', { k: 'sharad_navratri', end: 'sharad_navami', rule: ['आश्विन शुक्ल प्रतिपदा', 'Ashvina Shukla Pratipada'], r: 'all', guide: 'aarti/durga-aarti' }),
  T('ashvina', 'विजयादशमी / दशहरा', 'Vijayadashami / Dussehra', 'शुक्ल दशमी — राम द्वारा रावण वध; शमी व शस्त्र पूजन; गरबा/डांडिया का समापन।', 'Shukla Dashami — Ram’s victory over Ravana; shami and shastra puja; the close of garba/dandiya.', { k: 'dussehra', rule: ['आश्विन शुक्ल दशमी', 'Ashvina Shukla Dashami'], r: 'all' }),
  T('ashvina', 'शरद पूर्णिमा', 'Sharad Purnima', 'पूर्णिमा — महारास की तिथि; चाँदनी में रखी खीर का सेवन।', 'Purnima — the night of the Maharas; eating kheer left under the moonlight.', { k: 'sharad_purnima', rule: ['आश्विन पूर्णिमा', 'Ashvina Purnima'], r: 'all', guide: 'vrat/purnima' }),
  // ── Kartika ──
  T('kartika', 'करवा चौथ', 'Karwa Chauth', 'कृष्ण चतुर्थी — सुहागिनों का निर्जला व्रत; चंद्रमा को अर्घ्य।', 'Krishna Chaturthi — the waterless fast of married women; arghya to the Moon.', { k: 'karwa_chauth', rule: ['कार्तिक कृष्ण चतुर्थी', 'Kartika Krishna Chaturthi'], r: 'north', note: ['व्रत खुलने का समय चंद्रोदय पर निर्भर है, जो शहर-शहर बदलता है।', 'The time to break the fast depends on moonrise, which differs from city to city.'] }),
  T('kartika', 'अहोई अष्टमी', 'Ahoi Ashtami', 'कृष्ण अष्टमी — संतान की सुरक्षा हेतु स्याहू माता का पूजन।', 'Krishna Ashtami — worship of Syahu Mata for the safety of children.', { k: 'ahoi_ashtami', rule: ['कार्तिक कृष्ण अष्टमी', 'Kartika Krishna Ashtami'], r: 'north' }),
  T('kartika', 'धनतेरस', 'Dhanteras', 'कृष्ण त्रयोदशी — धन्वंतरि प्राकट्य; बर्तन/धातु की ख़रीद; यम दीपदान।', 'Krishna Trayodashi — appearance of Dhanvantari; buying utensils or metal; Yama deepdaan.', { k: 'dhanteras', rule: ['कार्तिक कृष्ण त्रयोदशी', 'Kartika Krishna Trayodashi'], r: 'all' }),
  T('kartika', 'नरक चतुर्दशी / रूप चौदस', 'Narak Chaturdashi / Roop Chaudas', 'कृष्ण चतुर्दशी — अभ्यंग स्नान, उबटन।', 'Krishna Chaturdashi — abhyanga snan and ubtan.', { k: 'naraka_chaturdashi', rule: ['कार्तिक कृष्ण चतुर्दशी', 'Kartika Krishna Chaturdashi'], r: 'all' }),
  T('kartika', 'दीपावली', 'Deepavali', 'अमावस्या — श्री लक्ष्मी-गणेश व कुबेर पूजन; दीपमाला।', 'Amavasya — worship of Lakshmi, Ganesh and Kubera; rows of lamps.', { k: 'diwali', rule: ['कार्तिक अमावस्या', 'Kartika Amavasya'], r: 'all', guide: 'aarti/lakshmi-aarti' }),
  T('kartika', 'गोवर्धन पूजा / गोधन', 'Govardhan Puja / Godhan', 'शुक्ल प्रतिपदा — अन्नकूट का भोग, गोवर्धन परिक्रमा; बिहार में गोधन कूटना।', 'Shukla Pratipada — Annakut offering, Govardhan parikrama; Godhan kutna in Bihar.', { k: 'govardhan', rule: ['कार्तिक शुक्ल प्रतिपदा', 'Kartika Shukla Pratipada'], r: 'north' }),
  T('kartika', 'भैया दूज / यम द्वितीया', 'Bhai Dooj / Yama Dwitiya', 'शुक्ल द्वितीया — यम-यमुना कथा; भाई को तिलक।', 'Shukla Dwitiya — the Yama–Yamuna katha; tilak for brothers.', { k: 'bhai_dooj', rule: ['कार्तिक शुक्ल द्वितीया', 'Kartika Shukla Dwitiya'], r: 'all' }),
  T('kartika', 'छठ पूजा', 'Chhath Puja', 'चार दिन — नहाय-खाय, खरना, अस्ताचलगामी सूर्य को संध्या अर्घ्य और उदीयमान सूर्य को उषा अर्घ्य (बिहार, पूर्वांचल और देश-विदेश)।', 'Four days — nahay-khay, kharna, the evening arghya to the setting Sun and the morning arghya to the rising Sun (Bihar, Purvanchal and across the world).', { k: 'chhath_sandhya', span: [-2, 1], rule: ['कार्तिक शुक्ल षष्ठी (संध्या अर्घ्य)', 'Kartika Shukla Shashthi (evening arghya)'], r: 'east' }),
  T('kartika', 'सामा-चकेवा', 'Sama-Chakeva', 'शुक्ल सप्तमी से पूर्णिमा (बिहार/मिथिला) — भाई-बहन के प्रेम का लोकपर्व।', 'Shukla Saptami to Purnima (Bihar/Mithila) — a folk festival of sibling love.', { info: true, r: 'east' }),
  T('kartika', 'देवउठनी एकादशी', 'Dev Uthani Ekadashi', 'शुक्ल एकादशी — विष्णु जागरण; गन्ने का मंडप; तुलसी विवाह का आरंभ।', 'Shukla Ekadashi — Vishnu’s awakening; sugarcane mandap; the start of Tulsi Vivah.', { k: 'dev_uthani', rule: ['कार्तिक शुक्ल एकादशी', 'Kartika Shukla Ekadashi'], r: 'all', guide: 'vrat/ekadashi' }),
  T('kartika', 'कार्तिक पूर्णिमा / देव दीपावली', 'Kartik Purnima / Dev Deepawali', 'पूर्णिमा — काशी में देव दीपावली; पवित्र नदियों में दीपदान।', 'Purnima — Dev Deepawali at Kashi; lamp offerings in sacred rivers.', { k: 'kartik_purnima', rule: ['कार्तिक पूर्णिमा', 'Kartika Purnima'], r: 'all', guide: 'vrat/purnima' }),
  // ── Margashirsha … Phalguna ──
  T('margashirsha', 'विवाह पंचमी', 'Vivah Panchami', 'शुक्ल पंचमी — श्री राम-सीता विवाह उत्सव।', 'Shukla Panchami — the celebration of Ram and Sita’s wedding.', { k: 'vivah_panchami', rule: ['मार्गशीर्ष शुक्ल पंचमी', 'Margashirsha Shukla Panchami'], r: 'all' }),
  T('pausha', 'पोंगल (तमिलनाडु)', 'Pongal (Tamil Nadu)', 'सूर्य देव को नया चावल-गुड़ (पोंगल) अर्पित करना; मट्टू पोंगल। मकर संक्रांति के आसपास।', 'Offering new rice and jaggery (pongal) to the Sun god; Mattu Pongal. Around Makar Sankranti.', { sol: 9, r: 'south' }),
  T('pausha', 'मकर संक्रांति / उत्तरायण', 'Makar Sankranti / Uttarayan', 'सूर्य का उत्तरायण; गुजरात में पतंगोत्सव; तिल-गुड़ का दान।', 'The Sun’s northward journey; kite festival in Gujarat; donating til-gud.', { sol: 9, r: 'all' }),
  T('magha', 'सकट चौथ / तिलकुटा', 'Sakat Chauth / Tilkuta', 'कृष्ण चतुर्थी — गणेश पूजन; तिल-गुड़ का भोग।', 'Krishna Chaturthi — Ganesh puja; til-gud offering.', { k: 'sakat_chauth', rule: ['माघ कृष्ण चतुर्थी', 'Magha Krishna Chaturthi'], r: 'north', guide: 'aarti/ganesh-aarti' }),
  T('magha', 'मौनी अमावस्या', 'Mauni Amavasya', 'माघ अमावस्या — प्रयागराज माघ मेले/कुंभ में स्नान; मौन व्रत।', 'Magha Amavasya — holy bath at the Prayagraj Magh Mela/Kumbh; a vow of silence.', { k: 'mauni_amavasya', rule: ['माघ अमावस्या', 'Magha Amavasya'], r: 'north', guide: 'vrat/amavasya' }),
  T('magha', 'बसंत पंचमी', 'Basant Panchami', 'शुक्ल पंचमी — माँ सरस्वती का पूजन; पीले वस्त्र और पीले चावल का भोग।', 'Shukla Panchami — worship of Goddess Saraswati; yellow clothes and yellow rice.', { k: 'basant_panchami', rule: ['माघ शुक्ल पंचमी', 'Magha Shukla Panchami'], r: 'all' }),
  T('phalguna', 'महाशिवरात्रि', 'Maha Shivratri', 'कृष्ण चतुर्दशी — शिव-पार्वती विवाह; रात्रि जागरण और अभिषेक।', 'Krishna Chaturdashi — the wedding of Shiva and Parvati; night vigil and abhishek.', { k: 'maha_shivratri', rule: ['फाल्गुन कृष्ण चतुर्दशी', 'Phalguna Krishna Chaturdashi'], r: 'all', guide: 'aarti/shiv-aarti' }),
  T('phalguna', 'होली / होलिका दहन', 'Holi / Holika Dahan', 'पूर्णिमा — प्रह्लाद रक्षा कथा; होलिका दहन और अगले दिन रंगों की धुलेंडी।', 'Purnima — the Prahlada story; Holika Dahan and, the next day, the Dhulandi festival of colours.', { k: 'holika_dahan', plus: 1, rule: ['फाल्गुन पूर्णिमा', 'Phalguna Purnima'], r: 'all', note: ['होलिका दहन भद्रा के बिना प्रदोष में होता है; ग्रहण/भद्रा पड़ने पर दिन बदल सकता है।', 'Holika Dahan is done in the evening, outside Bhadra; an eclipse or Bhadra can shift the day.'] }),
];

// Dates on which independent published calendars agreed (2026 only). Shown as a badge so readers see the commonly followed day.
export const PUBLISHED_2026 = {
  holika_dahan: '2026-03-03', chaitra_navratri: '2026-03-19', raksha_bandhan: '2026-08-28', janmashtami: '2026-09-04', ganesh_chaturthi: '2026-09-14',
  sharad_navratri: '2026-10-11', dussehra: '2026-10-20', karwa_chauth: '2026-10-29', dhanteras: '2026-11-06', diwali: '2026-11-08', govardhan: '2026-11-10',
  bhai_dooj: '2026-11-11', chhath_sandhya: '2026-11-15',
};
