// lib/gita.js — verses of the Bhagavad Gita (Sanskrit text is public domain). Meanings are written
// freshly for this site in plain words; they are reflections, not translations of any published edition.
export const GITA = [
  { ref: '2.47', sa: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।\nमा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥',
    hi: 'तुम्हारा अधिकार कर्म करने में है, उसके फल पर नहीं। फल की चिंता में कर्म मत छोड़ो और न ही कर्म न करने में आसक्त हो।',
    en: 'Your right is to the action, never to its fruits. Do not let the fruit be your motive, and do not slip into inaction.' },
  { ref: '2.48', sa: 'योगस्थः कुरु कर्माणि सङ्गं त्यक्त्वा धनञ्जय।\nसिद्ध्यसिद्ध्योः समो भूत्वा समत्वं योग उच्यते॥',
    hi: 'आसक्ति छोड़कर, सफलता-असफलता में सम रहकर कर्म करो — इसी समभाव को योग कहा गया है।',
    en: 'Act with steadiness, letting go of attachment and staying even in success and failure — that evenness is called yoga.' },
  { ref: '2.13', sa: 'देहिनोऽस्मिन्यथा देहे कौमारं यौवनं जरा।\nतथा देहान्तरप्राप्तिर्धीरस्तत्र न मुह्यति॥',
    hi: 'जैसे इस शरीर में बचपन, जवानी और बुढ़ापा आते हैं, वैसे ही आगे की अवस्था भी आती है; धीर व्यक्ति इसमें मोहित नहीं होता।',
    en: 'As childhood, youth and old age come in this body, so does what follows; the steady person is not bewildered by it.' },
  { ref: '2.22', sa: 'वासांसि जीर्णानि यथा विहाय\nनवानि गृह्णाति नरोऽपराणि।\nतथा शरीराणि विहाय जीर्णा-\nन्यन्यानि संयाति नवानि देही॥',
    hi: 'जैसे मनुष्य पुराने वस्त्र छोड़कर नए पहन लेता है, वैसे ही जीवात्मा पुराने शरीर छोड़कर नए धारण करती है।',
    en: 'Just as a person casts off worn clothes and puts on new ones, the self casts off worn bodies and takes new ones.' },
  { ref: '2.38', sa: 'सुखदुःखे समे कृत्वा लाभालाभौ जयाजयौ।\nततो युद्धाय युज्यस्व नैवं पापमवाप्स्यसि॥',
    hi: 'सुख-दुःख, लाभ-हानि और जय-पराजय को समान मानकर कर्तव्य में लगो — इस तरह तुम दोष से बचे रहोगे।',
    en: 'Treat pleasure and pain, gain and loss, victory and defeat alike, and then take up your duty — this way you stay free of fault.' },
  { ref: '3.19', sa: 'तस्मादसक्तः सततं कार्यं कर्म समाचर।\nअसक्तो ह्याचरन्कर्म परमाप्नोति पूरुषः॥',
    hi: 'इसलिए आसक्ति के बिना अपना कर्तव्य निरंतर करते रहो; आसक्ति-रहित कर्म करने वाला परम लक्ष्य को पाता है।',
    en: 'So keep doing what must be done, without attachment; one who acts unattached reaches the highest.' },
  { ref: '4.7', sa: 'यदा यदा हि धर्मस्य ग्लानिर्भवति भारत।\nअभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्॥',
    hi: 'जब-जब धर्म की हानि और अधर्म का उभार होता है, तब-तब मैं स्वयं को प्रकट करता हूँ।',
    en: 'Whenever righteousness declines and unrighteousness rises, I manifest myself.' },
  { ref: '4.38', sa: 'न हि ज्ञानेन सदृशं पवित्रमिह विद्यते।\nतत्स्वयं योगसंसिद्धः कालेनात्मनि विन्दति॥',
    hi: 'इस संसार में ज्ञान के समान पवित्र कुछ नहीं; योग में सिद्ध व्यक्ति उसे समय आने पर अपने भीतर पा लेता है।',
    en: 'Nothing here purifies like knowledge; one perfected in yoga finds it within, in time.' },
  { ref: '6.5', sa: 'उद्धरेदात्मनात्मानं नात्मानमवसादयेत्।\nआत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः॥',
    hi: 'अपने द्वारा अपना उद्धार करो, अपने को गिरने मत दो; क्योंकि मनुष्य स्वयं ही अपना मित्र है और स्वयं ही अपना शत्रु।',
    en: 'Lift yourself by your own effort; do not let yourself sink. You are your own friend, and you are your own enemy.' },
  { ref: '6.17', sa: 'युक्ताहारविहारस्य युक्तचेष्टस्य कर्मसु।\nयुक्तस्वप्नावबोधस्य योगो भवति दुःखहा॥',
    hi: 'जिसका खान-पान, विहार, कर्म, नींद और जागना संतुलित है, उसके लिए योग दुःख मिटाने वाला बनता है।',
    en: 'For one who is balanced in eating, recreation, work, sleep and waking, yoga becomes the remover of sorrow.' },
  { ref: '9.22', sa: 'अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते।\nतेषां नित्याभियुक्तानां योगक्षेमं वहाम्यहम्॥',
    hi: 'जो अनन्य भाव से मेरा चिंतन करते हुए उपासना करते हैं, उन निरंतर लगे हुए भक्तों का योग-क्षेम मैं वहन करता हूँ।',
    en: 'To those who worship me with undivided devotion, ever steadfast, I carry what they lack and protect what they have.' },
  { ref: '12.13', sa: 'अद्वेष्टा सर्वभूतानां मैत्रः करुण एव च।\nनिर्ममो निरहङ्कारः समदुःखसुखः क्षमी॥',
    hi: 'जो किसी से द्वेष नहीं करता, सबका मित्र और करुणावान है, ममता और अहंकार से रहित है, सुख-दुःख में सम है और क्षमाशील है — वह मुझे प्रिय है।',
    en: 'One who hates no creature, is friendly and compassionate, free of possessiveness and ego, even in pleasure and pain, and forgiving — such a person is dear to me.' },
  { ref: '17.15', sa: 'अनुद्वेगकरं वाक्यं सत्यं प्रियहितं च यत्।\nस्वाध्यायाभ्यसनं चैव वाङ्मयं तप उच्यते॥',
    hi: 'जो वाणी किसी को उद्वेग न दे, सत्य, प्रिय और हितकारी हो, और स्वाध्याय का अभ्यास — यह वाणी का तप कहलाता है।',
    en: 'Speech that does not agitate, that is true, pleasant and beneficial, along with regular study — this is called the discipline of speech.' },
  { ref: '18.66', sa: 'सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज।\nअहं त्वां सर्वपापेभ्यो मोक्षयिष्यामि मा शुचः॥',
    hi: 'सब धर्मों (कर्तव्यों की चिंता) को छोड़कर केवल मेरी शरण में आओ; मैं तुम्हें सब पापों से मुक्त करूँगा, शोक मत करो।',
    en: 'Setting aside all anxious duties, take refuge in me alone; I will free you from all sin — do not grieve.' },
  { ref: '18.78', sa: 'यत्र योगेश्वरः कृष्णो यत्र पार्थो धनुर्धरः।\nतत्र श्रीर्विजयो भूतिर्ध्रुवा नीतिर्मतिर्मम॥',
    hi: 'जहाँ योगेश्वर कृष्ण हैं और जहाँ धनुर्धारी अर्जुन हैं, वहीं श्री, विजय, ऐश्वर्य और अटल नीति है — ऐसा मेरा मत है।',
    en: 'Where Krishna, lord of yoga, and Arjuna the archer are, there are prosperity, victory, well-being and steady wisdom — so I hold.' },
];
export function gitaOfDay(isoDate) {
  const d = new Date(isoDate + 'T00:00:00Z');
  const dayNo = Math.floor(d.getTime() / 86400000);
  return GITA[((dayNo % GITA.length) + GITA.length) % GITA.length];
}
