// Traditional weekday associations (deity, colour, mantra); the practices are gentle, everyday actions.
export const UPAY = [
  { deity: ['सूर्य देव', 'Surya'], color: ['लाल / केसरिया', 'Red or saffron'], mantra: 'ॐ सूर्याय नमः', do: ['सुबह उगते सूर्य को जल दें और कुछ मिनट धूप में शांत बैठें।', 'Offer water to the rising Sun and sit quietly in the morning light for a few minutes.'], extra: ['पिता या गुरु का हाल पूछें।', 'Ask after your father or a teacher.'] },
  { deity: ['शिव जी', 'Shiva'], color: ['सफ़ेद', 'White'], mantra: 'ॐ नमः शिवाय', do: ['शिवलिंग पर जल चढ़ाएँ या पाँच मिनट शांत बैठकर मंत्र जपें।', 'Offer water at a Shivling or chant the mantra quietly for five minutes.'], extra: ['माँ या घर की बुज़ुर्ग महिला की सेवा करें।', 'Do some service for your mother or an elder woman at home.'] },
  { deity: ['हनुमान जी', 'Hanuman'], color: ['लाल', 'Red'], mantra: 'ॐ हनुमते नमः', do: ['हनुमान चालीसा पढ़ें या हनुमान मंदिर में दर्शन करें।', 'Read the Hanuman Chalisa or visit a Hanuman temple.'], extra: ['थोड़ा व्यायाम करें और गुस्से में पहले कुछ साँसें गिनें।', 'Exercise a little, and count a few breaths before reacting in anger.'] },
  { deity: ['गणेश जी', 'Ganesha'], color: ['हरा', 'Green'], mantra: 'ॐ गं गणपतये नमः', do: ['नया या ज़रूरी काम शुरू करने से पहले गणेश जी का स्मरण करें।', 'Remember Ganesha before starting a new or important task.'], extra: ['पक्षियों/गाय को दाना या हरा चारा दें।', 'Feed birds, or give green fodder to a cow.'] },
  { deity: ['विष्णु जी / गुरु', 'Vishnu / your teacher'], color: ['पीला', 'Yellow'], mantra: 'ॐ नमो भगवते वासुदेवाय', do: ['गुरु या शिक्षक का सम्मान करें और कुछ नया सीखें।', 'Honour a teacher and learn something new.'], extra: ['चना या केले जैसी पीली चीज़ किसी को दें।', 'Share something yellow, such as gram or bananas.'] },
  { deity: ['देवी लक्ष्मी / माँ', 'Goddess Lakshmi / the Mother'], color: ['सफ़ेद / गुलाबी', 'White or pink'], mantra: 'ॐ श्री महालक्ष्म्यै नमः', do: ['घर की सफ़ाई और सजावट करें; देवी के सामने दीपक जलाएँ।', 'Tidy and decorate the home; light a lamp before the Goddess.'], extra: ['किसी ज़रूरतमंद को वस्त्र या भोजन दें।', 'Give clothes or food to someone in need.'] },
  { deity: ['शनि देव', 'Shani'], color: ['नीला / काला', 'Blue or black'], mantra: 'ॐ शं शनैश्चराय नमः', do: ['अधूरे ज़िम्मेदारी वाले काम निपटाएँ और समय के पाबंद रहें।', 'Finish pending duties and keep to time.'], extra: ['श्रमिक, सफ़ाईकर्मी या ज़रूरतमंद की मदद करें; सरसों का तेल दान करें।', 'Help a worker, sanitation staff or someone in need; donate mustard oil.'] },
];

