// lib/vrat-guides.js — puja vidhi and katha for the recurring vrats. Written for this site in plain words from widely
// followed practice (traditions differ by family, region and sampradaya — every guide says so). Kathas are short retellings
// of traditional accounts; versions vary. No outcome is promised.
const S = (hi, en) => ({ hi, en });

export const COMMON_PUJA = {
  title: S('सामान्य पूजन विधि', 'General puja vidhi'),
  steps: [
    S('संकल्प व स्नान: प्रातः स्नान कर पवित्र भाव से पूजन का संकल्प लें।', 'Sankalp and bath: bathe early and take the resolve to perform the puja with a pure mind.'),
    S('स्थापना व दीप: चौकी पर स्वास्तिक बनाकर प्रतिमा/चित्र स्थापित करें और दीप प्रज्वलित करें।', 'Sthapana and lamp: draw a swastika on a wooden seat, place the image or idol, and light a lamp.'),
    S('पंचोपचार/षोडशोपचार: जल, रोली, अक्षत, पुष्प, धूप, दीप और नैवेद्य अर्पित करें।', 'Panchopachar / shodashopachar: offer water, roli, rice, flowers, incense, lamp and naivedya.'),
    S('आरती व विसर्जन: कथा श्रवण के बाद आरती करें और प्रसाद बाँटें।', 'Aarti and conclusion: after hearing the katha, do the aarti and distribute the prasad.'),
  ],
};

export const VRATS = [
  {
    slug: 'ekadashi', glyph: '☊', cal: 'ekadashi', aarti: 'om-jai-jagdish-hare',
    hi: 'एकादशी व्रत', en: 'Ekadashi Vrat', deity: S('भगवान विष्णु', 'Lord Vishnu'),
    about: S('हर पक्ष (शुक्ल और कृष्ण) की ग्यारहवीं तिथि एकादशी कहलाती है और भगवान विष्णु को समर्पित है। साल में सामान्यतः 24 एकादशी आती हैं (अधिक मास में 26)।', 'The eleventh tithi of each paksha (Shukla and Krishna) is Ekadashi, dedicated to Lord Vishnu. There are normally 24 Ekadashis in a year (26 in a year with an adhika masa).'),
    niyam: [
      S('दशमी की शाम सूर्यास्त से पहले सात्त्विक, हल्का भोजन करें।', 'On Dashami eat a light, sattvic meal before sunset.'),
      S('एकादशी को अन्न (चावल, गेहूँ, दालें), प्याज-लहसुन, मांस और मदिरा से दूर रहें। फल, दूध, मेवे, साबूदाना, कुट्टू/सिंघाड़े का आटा और आलू परंपरा में चलते हैं।', 'On Ekadashi avoid grains (rice, wheat, pulses), onion-garlic, meat and alcohol. Fruit, milk, dry fruit, sabudana, kuttu or singhara flour and potato are traditionally allowed.'),
      S('तुलसी के पत्ते एकादशी को न तोड़ें — दशमी या उससे पहले तोड़कर रख लें।', 'Do not pluck tulsi leaves on Ekadashi — gather them on Dashami or earlier.'),
      S('दिन में सोने, क्रोध और कठोर बोली से बचें; भजन-कीर्तन और विष्णु नाम-जप करें।', 'Avoid sleeping in the day, anger and harsh speech; spend the day in bhajan and chanting Vishnu’s name.'),
    ],
    samagri: S('भगवान विष्णु की प्रतिमा/चित्र या शालिग्राम, पीला वस्त्र, पीले फूल, तुलसी पत्र, पंचामृत (दूध, दही, घी, शहद, शक्कर), फल, धूप, घी का दीपक, चंदन/रोली, अक्षत।', 'An image of Lord Vishnu or a Shaligram, yellow cloth, yellow flowers, tulsi leaves, panchamrit (milk, curd, ghee, honey, sugar), fruit, incense, a ghee lamp, sandal or roli, rice grains.'),
    vidhi: [
      S('प्रातः स्नान करके साफ़ वस्त्र पहनें और पूजा-स्थान स्वच्छ करें।', 'Bathe early, wear clean clothes and clean the puja place.'),
      S('हाथ में जल, अक्षत और पुष्प लेकर व्रत का संकल्प करें: “मैं भगवान विष्णु की प्रसन्नता के लिए एकादशी का व्रत करता/करती हूँ।”', 'Take water, rice and a flower in your hand and resolve: “I observe the Ekadashi vrat for the grace of Lord Vishnu.”'),
      S('चौकी पर पीला वस्त्र बिछाकर भगवान विष्णु की प्रतिमा/चित्र स्थापित करें और दीपक जलाएँ।', 'Spread a yellow cloth on a seat, place the image of Lord Vishnu and light the lamp.'),
      S('जल व पंचामृत से अभिषेक करें, फिर चंदन-रोली, पीले फूल और तुलसी पत्र अर्पित करें।', 'Do abhishek with water and panchamrit, then offer sandal-roli, yellow flowers and tulsi leaves.'),
      S('धूप-दीप दिखाकर फल व मिष्ठान्न का भोग लगाएँ (भोग में तुलसी अवश्य रखें)।', 'Show incense and lamp and offer fruit and sweets (always with a tulsi leaf).'),
      S('“ॐ नमो भगवते वासुदेवाय” का 108 बार जप करें; चाहें तो विष्णु सहस्रनाम पढ़ें।', 'Chant “Om Namo Bhagavate Vasudevaya” 108 times; you may also read the Vishnu Sahasranama.'),
      S('एकादशी की कथा पढ़ें या सुनें, फिर आरती करें (ॐ जय जगदीश हरे) और प्रसाद बाँटें।', 'Read or hear the Ekadashi katha, then do the aarti (Om Jai Jagdish Hare) and share the prasad.'),
      S('शाम को तुलसी के पास दीपक जलाएँ; रात में भजन या जागरण करें।', 'In the evening light a lamp near the tulsi plant; spend the night in bhajans or a vigil.'),
    ],
    parana: S('पारण द्वादशी के दिन सूर्योदय के बाद, द्वादशी तिथि के भीतर करें और हरि-वासर (द्वादशी का पहला चौथाई भाग) में पारण न करें। पहले तुलसी-जल या प्रसाद लें, फिर सात्त्विक अन्न ग्रहण करें और यथाशक्ति दान दें। सटीक पारण-समय के लिए स्थानीय पंचांग देखें।', 'Break the fast on Dwadashi after sunrise and within the Dwadashi tithi, but not during Hari Vasara (the first quarter of Dwadashi). Take tulsi water or prasad first, then a sattvic meal, and give what you can in charity. Check a local almanac for the exact parana window.'),
    note: S('स्मार्त और वैष्णव परंपराओं में, विशेषकर जब दशमी एकादशी में मिली हो, व्रत का दिन अलग हो सकता है। अपनी परंपरा के अनुसार चलें।', 'Smarta and Vaishnava traditions can differ on the day, especially when Dashami overlaps Ekadashi. Follow your own tradition.'),
    mantra: 'ॐ नमो भगवते वासुदेवाय',
    katha: { title: S('एकादशी की उत्पत्ति की कथा', 'The origin of Ekadashi'), body: [
      S('पुराणों में कथा आती है कि सत्ययुग में मुर नाम का बलशाली दैत्य था। उसने देवताओं को स्वर्ग से निकाल दिया। दुखी देवता भगवान शिव के पास गए, और शिव जी ने उन्हें भगवान विष्णु की शरण में भेजा।', 'The Puranas tell that in the Satya Yuga there was a mighty demon named Mura who drove the devas out of heaven. Distressed, they went to Lord Shiva, who sent them to take refuge in Lord Vishnu.'),
      S('विष्णु जी ने मुर से बहुत समय तक युद्ध किया। थककर वे बद्रिकाश्रम की एक गुफ़ा (हिमावती) में विश्राम करने लगे। मुर ने सोते हुए प्रभु पर आक्रमण करना चाहा।', 'Vishnu fought Mura for a very long time. Tired, he rested in a cave (Himavati) at Badrikashram. Mura tried to attack the sleeping Lord.'),
      S('तभी भगवान के शरीर से एक तेजस्वी कन्या प्रकट हुई और उसने मुर का वध कर दिया। जागने पर विष्णु जी प्रसन्न हुए। कन्या ने कहा कि वह उन्हीं की शक्ति से उत्पन्न एकादशी है।', 'Then a radiant maiden emerged from the Lord’s body and slew Mura. Waking, Vishnu was pleased. She said she was born of his own power — Ekadashi.'),
      S('प्रभु ने उसे वरदान दिया कि जो श्रद्धा से इस तिथि का व्रत करेगा, उसके पाप क्षीण होंगे और वह विष्णु-धाम का अधिकारी होगा। तभी से एकादशी का व्रत किया जाता है।', 'The Lord granted her a boon: whoever fasts on this tithi with faith will have sins diminished and attain Vishnu’s abode. Since then Ekadashi is observed.'),
    ] },
  },
  {
    slug: 'purnima', glyph: '○', cal: 'purnima', aarti: 'om-jai-jagdish-hare',
    hi: 'पूर्णिमा व्रत और सत्यनारायण पूजा', en: 'Purnima Vrat & Satyanarayan Puja', deity: S('भगवान सत्यनारायण (विष्णु) और चंद्र देव', 'Lord Satyanarayan (Vishnu) and the Moon'),
    about: S('हर माह की शुक्ल पक्ष की अंतिम तिथि पूर्णिमा है। इस दिन सत्यनारायण भगवान की पूजा-कथा, पवित्र नदी में स्नान, दान और चंद्र दर्शन की परंपरा है।', 'The last tithi of each Shukla paksha is Purnima. Satyanarayan puja and katha, a holy bath, charity and sighting the Moon are traditional on this day.'),
    niyam: [
      S('प्रातः स्नान (संभव हो तो गंगा-जल मिलाकर) और सात्त्विक भोजन।', 'Bathe early (adding Ganga jal if possible) and eat sattvic food.'),
      S('व्रत सूर्योदय से पूजा तक या चंद्रोदय तक रखा जा सकता है — अपनी परंपरा और क्षमता के अनुसार।', 'The fast may be kept from sunrise until the puja, or until moonrise — according to your tradition and ability.'),
      S('इस दिन ज़रूरतमंद को अन्न, वस्त्र या दक्षिणा का दान करें।', 'Give food, clothes or dakshina to someone in need.'),
      S('वादा करके सत्यनारायण पूजा टालना ठीक नहीं माना जाता — कथा की यही सीख है।', 'Postponing a promised Satyanarayan puja is not considered right — that is the lesson of the katha.'),
    ],
    samagri: S('सत्यनारायण भगवान का चित्र/मूर्ति, कलश, केले के पत्ते या खंभे (वैकल्पिक), पंचामृत, तुलसी पत्र, पीले फूल, फल, पान-सुपारी, रोली-चावल, धूप-दीप, और प्रसाद (सूजी/आटे का हलवा या पंजीरी के साथ केला)।', 'An image or idol of Satyanarayan, a kalash, plantain leaves or pillars (optional), panchamrit, tulsi leaves, yellow flowers, fruit, betel leaf and nut, roli and rice, incense and lamp, and prasad (semolina or wheat-flour halwa, or panjiri, with banana).'),
    vidhi: [
      S('स्नान कर पूजा-स्थान साफ़ करें और संकल्प लें।', 'Bathe, clean the puja place and take the sankalp.'),
      S('चौकी पर पीला वस्त्र बिछाएँ, कलश स्थापित करें और भगवान सत्यनारायण का चित्र/मूर्ति रखें।', 'Spread a yellow cloth on a seat, set up the kalash and place the image or idol of Satyanarayan.'),
      S('सबसे पहले गणेश जी का स्मरण-पूजन करें।', 'First remember and worship Ganesha.'),
      S('पंचामृत से स्नान कराकर चंदन, पीले फूल और तुलसी पत्र अर्पित करें।', 'Bathe the deity with panchamrit and offer sandal, yellow flowers and tulsi leaves.'),
      S('प्रसाद (केले सहित) का भोग लगाएँ।', 'Offer the prasad (with banana).'),
      S('सत्यनारायण व्रत कथा के अध्याय पढ़ें या सुनें।', 'Read or hear the chapters of the Satyanarayan vrat katha.'),
      S('आरती करें (ॐ जय जगदीश हरे) और प्रसाद सबमें बाँटें।', 'Do the aarti (Om Jai Jagdish Hare) and share the prasad with everyone.'),
      S('शाम को चंद्रोदय पर चंद्रमा को जल/दूध का अर्घ्य दें और व्रत खोलें।', 'In the evening offer water or milk to the Moon at moonrise and break the fast.'),
    ],
    parana: S('चंद्रमा को अर्घ्य देने या पूजा-प्रसाद के बाद सात्त्विक भोजन से व्रत खोलें।', 'Break the fast with a sattvic meal after offering arghya to the Moon or after the puja prasad.'),
    note: S('यह कथा का संक्षिप्त सार है; पूरी कथा पाँच अध्यायों की है और अलग-अलग पुस्तकों में थोड़ी भिन्न मिलती है।', 'This is a short summary; the full katha has five chapters and differs slightly between books.'),
    mantra: 'ॐ नमो नारायणाय',
    katha: { title: S('सत्यनारायण कथा (संक्षेप)', 'Satyanarayan katha (in brief)'), body: [
      S('नारद मुनि ने पृथ्वी पर लोगों के कष्ट देखे और भगवान विष्णु से सरल उपाय पूछा। प्रभु ने सत्यनारायण व्रत का महत्त्व बताया।', 'Sage Narada saw people’s sufferings on earth and asked Lord Vishnu for an easy remedy. The Lord described the Satyanarayan vrat.'),
      S('काशी के एक निर्धन ब्राह्मण के पास वृद्ध ब्राह्मण के रूप में स्वयं विष्णु जी आए और यह व्रत बताया। उसने श्रद्धा से व्रत किया तो उसकी दरिद्रता दूर हुई और वह हर पूर्णिमा को पूजा करने लगा। इसी तरह एक लकड़हारे ने भी व्रत किया और उसे अपने श्रम का अच्छा फल मिला।', 'To a poor Brahmin of Kashi, Vishnu himself came as an old Brahmin and told him of the vrat. He performed it with faith, his poverty ended and he began to worship every Purnima. A woodcutter too did the vrat and was rewarded well for his labour.'),
      S('साधु नाम के एक वणिक ने संतान होने पर पूजा का वचन दिया, पर उसे टालता रहा; बाद में उसकी नाव और धन संकट में पड़ गए। अपनी भूल मानकर जब उसने पूजा की तो संकट टल गया। एक राजा और उसकी पुत्री कलावती की कथाओं में प्रसाद की उपेक्षा करने पर कष्ट और श्रद्धा से प्रसाद लेने पर कृपा की सीख आती है।', 'A merchant named Sadhu vowed to do the puja when a child was born but kept postponing; later his boat and wealth fell into trouble. When he admitted his lapse and did the puja, the trouble passed. The stories of a king and of the merchant’s daughter Kalavati teach that disrespecting the prasad brings hardship, and accepting it with faith brings grace.'),
      S('कथा की सीख: सत्य का पालन करें, किया हुआ वादा निभाएँ और प्रसाद का आदर करें।', 'The lesson: stay truthful, keep your promises and honour the prasad.'),
    ] },
  },
  {
    slug: 'amavasya', glyph: '●', cal: 'amavasya', aarti: null,
    hi: 'अमावस्या — पितृ-स्मरण, स्नान और दान', en: 'Amavasya — remembering ancestors, bath and charity', deity: S('पितृ (पूर्वज), भगवान विष्णु व शिव', 'Pitrus (ancestors), Lord Vishnu and Shiva'),
    about: S('अमावस्या (अमावस) कृष्ण पक्ष की अंतिम तिथि है। इसे पितरों के स्मरण, तर्पण, दान और स्नान की तिथि माना जाता है। सोमवार को पड़े तो सोमवती अमावस्या, शनिवार को शनि अमावस्या और माघ में मौनी अमावस्या कहलाती है।', 'Amavasya (the new-moon day) is the last tithi of Krishna paksha. It is held a day for remembering ancestors, tarpan, charity and a holy bath. When it falls on a Monday it is Somvati Amavasya, on a Saturday Shani Amavasya, and in Magha it is Mauni Amavasya.'),
    niyam: [
      S('प्रातः नदी या घर पर स्नान करें; संभव हो तो गंगा-जल मिलाएँ।', 'Bathe early at a river or at home; add Ganga jal if possible.'),
      S('तर्पण और पितरों के नाम से दान — अन्न, वस्त्र, तिल, कंबल (सर्दी में)।', 'Do tarpan and give in the name of ancestors — food, clothes, sesame, blankets (in winter).'),
      S('गाय, कुत्ते, कौए और चींटियों को भोजन दें।', 'Feed cows, dogs, crows and ants.'),
      S('परंपरा में इस दिन नए शुभ कार्य शुरू करने से बचा जाता है; सात्त्विक भोजन करें।', 'Traditionally new auspicious ventures are avoided on this day; eat sattvic food.'),
    ],
    samagri: S('कुशा, काले तिल, जल, दूध, चावल/जौ, तांबे या पीतल का पात्र, सात्त्विक भोजन, दीपक (घी या सरसों का तेल)।', 'Kusha grass, black sesame, water, milk, rice or barley, a copper or brass vessel, sattvic food and a lamp (ghee or mustard oil).'),
    vidhi: [
      S('स्नान के बाद साफ़ वस्त्र पहनकर संकल्प लें।', 'After the bath wear clean clothes and take the sankalp.'),
      S('दक्षिण दिशा की ओर मुख करके कुशा, काले तिल, जल (और थोड़ा दूध) से पितरों को जलांजलि दें।', 'Facing south, offer water mixed with black sesame, kusha (and a little milk) to the ancestors.'),
      S('घर पर बना सात्त्विक भोजन पितरों के निमित्त निकालें और गाय, कुत्ते व कौए को दें।', 'Set aside sattvic food cooked at home for the ancestors and give it to a cow, a dog and a crow.'),
      S('ज़रूरतमंद या ब्राह्मण को भोजन/दान दें।', 'Give food or charity to a needy person or a Brahmin.'),
      S('शाम को पीपल के नीचे या घर के दक्षिण कोने में दीपक जलाएँ और पितरों का स्मरण करें।', 'In the evening light a lamp under a peepal tree or in the south corner of the house and remember the ancestors.'),
      S('“ॐ पितृ देवाय नमः” का जप करें और शिव/विष्णु जी का स्मरण करें।', 'Chant “Om Pitri Devaya Namah” and remember Shiva or Vishnu.'),
    ],
    parana: null,
    note: S('सर्वपितृ अमावस्या (आश्विन) पर श्राद्ध की पूरी विधि के लिए श्राद्ध वाला पृष्ठ देखें।', 'For the full shraddh procedure on Sarva Pitru Amavasya (Ashvina), see the Shraddh page.'),
    mantra: 'ॐ पितृ देवाय नमः',
    katha: { title: S('कर्ण और पितरों के भोजन की कथा (लोक-परंपरा)', 'Karna and the food for the ancestors (folk tradition)'), body: [
      S('लोक-परंपरा में कथा आती है कि महाभारत के दानवीर कर्ण ने जीवन भर सोना-चाँदी दान किया, पर अन्न का दान नहीं किया। मृत्यु के बाद स्वर्ग में उन्हें भोजन के रूप में सोना ही मिला।', 'Folk tradition tells that Karna of the Mahabharata, famed for giving, donated gold and silver all his life but never food. After death, in heaven he was given only gold to eat.'),
      S('कर्ण ने कारण पूछा तो इंद्र ने बताया कि उसने कभी अन्न-जल से पितरों और ज़रूरतमंदों की सेवा नहीं की। तब कर्ण को पृथ्वी पर लौटकर अन्न और जल का दान करने का अवसर दिया गया।', 'When Karna asked why, Indra explained that he had never served his ancestors and the needy with food and water. Karna was then allowed to return to earth to give food and water.'),
      S('माना जाता है कि वही अवधि पितृपक्ष कहलाई। कथा की सीख है कि पूर्वजों के निमित्त अन्न-जल का दान सबसे बड़ा स्मरण है।', 'That period is believed to be Pitru Paksha. The lesson: giving food and water in the name of ancestors is the truest remembrance.'),
    ] },
  },
  {
    slug: 'pradosh', glyph: '☽', cal: 'pradosh', aarti: 'shiv-aarti',
    hi: 'प्रदोष व्रत', en: 'Pradosh Vrat', deity: S('भगवान शिव', 'Lord Shiva'),
    about: S('हर पक्ष की त्रयोदशी को प्रदोष व्रत होता है (महीने में दो बार)। सूर्यास्त के आसपास की संध्या का समय प्रदोष काल कहलाता है और उसी में शिव पूजा की जाती है। वार के अनुसार इसे सोम प्रदोष, भौम प्रदोष, शनि प्रदोष आदि कहते हैं।', 'Pradosh vrat falls on the Trayodashi of each paksha (twice a month). The twilight around sunset is Pradosh Kaal, and Shiva is worshipped in it. By weekday it is called Som Pradosh, Bhauma Pradosh, Shani Pradosh and so on.'),
    niyam: [
      S('दिन में उपवास रखें (फल/जल या अपनी क्षमता के अनुसार)।', 'Fast through the day (fruit and water, or as you are able).'),
      S('शाम की पूजा से पहले स्नान करें और स्वच्छ, हल्के रंग के वस्त्र पहनें।', 'Bathe before the evening puja and wear clean, light-coloured clothes.'),
      S('पूजा सूर्यास्त के आसपास, प्रदोष काल में करें (सटीक समय के लिए पंचांग देखें)।', 'Perform the puja around sunset, in Pradosh Kaal (check the almanac for the exact window).'),
    ],
    samagri: S('शिवलिंग या शिव-परिवार का चित्र, जल, दूध, दही, घी, शहद, गंगा-जल, बेलपत्र, सफ़ेद फूल, भस्म/चंदन, धूप-दीप, फल।', 'A Shivling or a picture of the Shiva family, water, milk, curd, ghee, honey, Ganga jal, bel leaves, white flowers, ash or sandal, incense and lamp, and fruit.'),
    vidhi: [
      S('दिन भर उपवास रखकर शाम को स्नान करें और पूजा-स्थान साफ़ करें।', 'Fast through the day, bathe in the evening and clean the puja place.'),
      S('प्रदोष काल में शिवलिंग का जल, दूध, दही, घी, शहद से अभिषेक करें, फिर शुद्ध जल से स्नान कराएँ।', 'In Pradosh Kaal do abhishek of the Shivling with water, milk, curd, ghee and honey, then bathe it with clean water.'),
      S('बेलपत्र, सफ़ेद फूल, चंदन/भस्म और धूप-दीप अर्पित करें।', 'Offer bel leaves, white flowers, sandal or ash, incense and lamp.'),
      S('“ॐ नमः शिवाय” का 108 बार जप करें।', 'Chant “Om Namah Shivaya” 108 times.'),
      S('प्रदोष व्रत की कथा पढ़ें या सुनें।', 'Read or hear the Pradosh vrat katha.'),
      S('शिव आरती (ॐ जय शिव ओंकारा) करें। परिक्रमा परंपरा से आधी की जाती है — जलहरी (गौमुख) को लाँघा नहीं जाता।', 'Do the Shiv aarti (Om Jai Shiv Omkara). The parikrama is traditionally half — the water channel (gaumukhi) is not crossed.'),
      S('प्रसाद बाँटकर सात्त्विक भोजन से व्रत खोलें।', 'Share the prasad and break the fast with a sattvic meal.'),
    ],
    parana: S('पूजा और आरती के बाद उसी शाम सात्त्विक भोजन से व्रत खोला जाता है।', 'After the puja and aarti the fast is broken the same evening with a sattvic meal.'),
    note: S('प्रदोष का दिन तिथि के त्रयोदशी में सूर्यास्त के समय होने से तय होता है; कभी-कभी वह दो दिनों की तिथि में आती है — पंचांग से पुष्टि करें।', 'The day is fixed by Trayodashi prevailing at sunset; sometimes it straddles two days — confirm with the almanac.'),
    mantra: 'ॐ नमः शिवाय',
    katha: { title: S('प्रदोष व्रत की कथा', 'The Pradosh vrat katha'), body: [
      S('स्कंद पुराण की कथा के अनुसार एक विधवा ब्राह्मणी अपने पुत्र के साथ भिक्षा से जीवन चलाती थी। एक दिन उसे विदर्भ का एक राजकुमार धर्मगुप्त मिला, जिसके पिता को शत्रुओं ने मार दिया था। ब्राह्मणी ने उसे अपने पुत्र की तरह रखा।', 'In the story from the Skanda Purana, a widowed Brahmin woman lived on alms with her son. One day she found Dharmagupta, a prince of Vidarbha whose father had been killed by enemies. She raised him as her own son.'),
      S('शांडिल्य ऋषि की सलाह पर उन्होंने प्रदोष व्रत करना शुरू किया। कुछ समय बाद राजकुमार की भेंट गंधर्व कन्या अंशुमती से हुई और गंधर्वराज की सहायता से उसने अपना राज्य वापस पाया। उसने ब्राह्मणी के पुत्र को अपना मंत्री बनाया।', 'On the advice of Sage Shandilya they began the Pradosh vrat. In time the prince met the gandharva maiden Anshumati and, with the gandharva king’s help, won his kingdom back, making the Brahmin woman’s son his minister.'),
      S('कथा की सीख है कि श्रद्धा से किया गया प्रदोष व्रत कठिन समय में संबल देता है। प्रदोष के पीछे समुद्र-मंथन की मान्यता भी है — हलाहल विष पीने के बाद देवताओं ने शिव जी की स्तुति संध्या में की थी।', 'The lesson is that a Pradosh vrat kept with faith gives strength in hard times. Tradition also links Pradosh to the churning of the ocean — after Shiva drank the Halahala poison, the devas praised him at twilight.'),
    ] },
  },
  {
    slug: 'shraddh', glyph: '🪔', cal: null, aarti: null,
    hi: 'पितृपक्ष / श्राद्ध के नियम', en: 'Pitru Paksha / Shraddh rules', deity: S('पितृ (पूर्वज)', 'Pitrus (ancestors)'),
    about: S('पितृपक्ष भाद्रपद पूर्णिमा से आश्विन अमावस्या तक के 16 दिन हैं, जिनमें पूर्वजों के निमित्त तर्पण, पिंडदान और श्राद्ध किया जाता है। जिस तिथि को पूर्वज का देहांत हुआ हो, उसी तिथि पर श्राद्ध करते हैं; तिथि न पता हो तो सर्वपितृ अमावस्या पर। (उत्तर भारत की पूर्णिमांत गणना में इसे आश्विन कृष्ण पक्ष कहते हैं।)', 'Pitru Paksha is the sixteen days from Bhadrapada Purnima to Ashvina Amavasya, in which tarpan, pind daan and shraddh are done for the ancestors. Shraddh is done on the tithi of the ancestor’s death, or on Sarva Pitru Amavasya if the tithi is unknown. (In the North Indian purnimanta count this is called Ashvina Krishna paksha.)'),
    niyam: [
      S('समय: श्राद्ध दोपहर के कुतप काल में करें — दिन का आठवाँ मुहूर्त, लगभग 11:30 से 12:30 के बीच (सटीक समय पंचांग में देखें)।', 'Time: perform shraddh in the kutapa kaal — the eighth muhurta of the day, roughly between 11:30 and 12:30 (see the almanac for the exact time).'),
      S('तर्पण: दक्षिण दिशा की ओर मुख करके कुशा, काले तिल, जल और थोड़े दूध से जलांजलि दें।', 'Tarpan: facing south, offer water with kusha, black sesame and a little milk.'),
      S('पंचबली: भोजन परोसने से पहले पाँच अंश निकालें — गाय, कुत्ता, कौआ, देवता और चींटी के लिए।', 'Panchabali: before serving, set aside five portions — for the cow, dog, crow, devas and ants.'),
      S('पिंडदान: चावल/जौ और तिल से पिंड बनाएँ; सात्त्विक भोजन (खीर-पूरी) कराकर दक्षिणा दें।', 'Pind daan: make pindas of rice or barley and sesame; feed a sattvic meal (kheer-puri) and give dakshina.'),
      S('परंपरा में माता के श्राद्ध के लिए मातृ नवमी और अज्ञात तिथि के लिए सर्वपितृ अमावस्या विशेष मानी जाती हैं।', 'Tradition marks Matri Navami for mothers and Sarva Pitru Amavasya for an unknown tithi.'),
    ],
    samagri: S('कुशा, काले तिल, जौ/चावल, जल, दूध, तांबे का पात्र, सात्त्विक भोजन (खीर-पूरी), दक्षिणा।', 'Kusha, black sesame, barley or rice, water, milk, a copper vessel, a sattvic meal (kheer-puri) and dakshina.'),
    vidhi: [
      S('स्नान कर संकल्प लें और अपने पितरों का नाम-गोत्र सहित स्मरण करें।', 'Bathe, take the sankalp and remember the ancestors by name and gotra.'),
      S('कुतप काल में दक्षिण दिशा की ओर मुख करके तर्पण करें।', 'In the kutapa kaal, face south and do the tarpan.'),
      S('पिंड बनाकर अर्पित करें।', 'Make and offer the pindas.'),
      S('पंचबली के अंश निकालकर गाय, कुत्ते, कौए, देवता और चींटी को दें।', 'Set aside the panchabali portions and give them to the cow, dog, crow, devas and ants.'),
      S('ब्राह्मण/ज़रूरतमंद को भोजन कराएँ और दक्षिणा दें; फिर परिवार सहित प्रसाद ग्रहण करें।', 'Feed a Brahmin or a needy person and give dakshina; then the family takes the prasad.'),
    ],
    parana: null,
    note: S('श्राद्ध की विधि परिवार, गोत्र और क्षेत्र की परंपरा से बदलती है। गया, हरिद्वार और प्रयाग जैसे तीर्थों में पिंडदान का विशेष महत्त्व माना जाता है। पक्की विधि के लिए अपने कुल-पुरोहित से पूछें।', 'The procedure varies with family, gotra and region. Pind daan at tirthas such as Gaya, Haridwar and Prayag is held especially meritorious. Ask your family priest for the exact procedure.'),
    mantra: 'ॐ पितृ देवाय नमः',
    katha: null,
  },
];
export const vratBySlug = (s) => VRATS.find(v => v.slug === s) || null;
