#!/usr/bin/env python3
"""Generates lib/panchang-data.js — exact transition instants of the five panchang elements with pyswisseph
(Lahiri ayanamsa, Moshier ephemeris, apparent positions). Instants are GLOBAL (not city-specific); the website
converts them to IST and picks what prevails at each city's own sunrise.
Run:  pip install pyswisseph && python3 scripts/generate-panchang-data.py [START_YEAR] [END_YEAR]
Re-run once a year to extend the range.  Format: each table is a flat list [m0, i0, m1, i1, ...] where m = minutes
since 2025-01-01T00:00Z (rounded to a minute) at which the element BECOMES index i."""
import sys, os, json, datetime as dt
import swisseph as swe
swe.set_sid_mode(swe.SIDM_LAHIRI)
EPOCH = dt.datetime(2025, 1, 1)
FL = swe.FLG_SIDEREAL

def jd_from_min(m): return swe.julday(2025, 1, 1, 0.0) + m / 1440.0
def moon(jd): return swe.calc_ut(jd, swe.MOON, FL)[0][0] % 360
def sun(jd):  return swe.calc_ut(jd, swe.SUN, FL)[0][0] % 360

QUANT = {
    'tithi':    (lambda jd: (moon(jd) - sun(jd)) % 360, 12.0),
    'karana':   (lambda jd: (moon(jd) - sun(jd)) % 360, 6.0),
    'nakshatra':(lambda jd: moon(jd), 360 / 27),
    'yoga':     (lambda jd: (moon(jd) + sun(jd)) % 360, 360 / 27),
    'moonsign': (lambda jd: moon(jd), 30.0),
    'sunsign':  (lambda jd: sun(jd), 30.0),
}

def transitions(name, m0, m1, step=90):
    f, unit = QUANT[name]
    idx = lambda m: int(f(jd_from_min(m)) // unit)
    n = int(360 // unit)
    m, i = m0, idx(m0)
    out = [[m0, i]]                                           # initial state, so lookups work before the first change
    while m < m1:
        nm = m + step; ni = idx(nm)
        if ni != i:
            lo, hi = m, nm                                    # a boundary lies in (lo, hi]; bisect to 0.01 minute
            for _ in range(40):
                mid = (lo + hi) / 2
                if idx(mid) == i: lo = mid
                else: hi = mid
            out.append([round(hi), ni]); i = ni
        m = nm
    out.append([m1, i])                                       # end sentinel (state unchanged)
    return out

if __name__ == '__main__':
    y0 = int(sys.argv[1]) if len(sys.argv) > 1 else 2026
    y1 = int(sys.argv[2]) if len(sys.argv) > 2 else 2029
    m0 = int((dt.datetime(y0, 1, 1) - dt.timedelta(days=3) - EPOCH).total_seconds() // 60)
    m1 = int((dt.datetime(y1, 12, 31) + dt.timedelta(days=4) - EPOCH).total_seconds() // 60)
    tables = {k: transitions(k, m0, m1) for k in QUANT}
    flat = {k: [x for pair in v for x in pair] for k, v in tables.items()}
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'lib')
    with open(os.path.join(root, 'panchang-data.js'), 'w', encoding='utf8') as fh:
        fh.write(f'// GENERATED by scripts/generate-panchang-data.py — exact panchang element transitions, {y0}-{y1}.\n'
                 f'// Lahiri ayanamsa, Moshier ephemeris. Minutes since 2025-01-01T00:00Z. Do not edit by hand.\n'
                 f'export const PANCHANG_RANGE = {json.dumps([y0, y1])};\n'
                 f'export const PANCHANG_EPOCH_UTC = Date.UTC(2025, 0, 1);\n'
                 f'export const PANCHANG_TABLES = {json.dumps(flat, separators=(",", ":"))};\n')
    print({k: len(v) for k, v in tables.items()}, 'bytes', os.path.getsize(os.path.join(root, 'panchang-data.js')))
